<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NetworkPortAnalyzer.Protocols\NetworkPortAnalyzer.Protocols.csproj" />
    <ProjectReference Include="..\..\src\NetworkPortAnalyzer.Windows\NetworkPortAnalyzer.Windows.csproj" />
  </ItemGroup>
</Project>
